server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    location = /health.json {
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }

    location = /version.json {
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
